/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package petshop;

/**
 *
 * @author isn
 */

import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.sql.*;
import java.util.regex.PatternSyntaxException;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

public class FLaporanTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FLaporanTransaksi
     */
    koneksi dbsetting;
    String driver,database,user,pass;
    int row=0;
    private TableRowSorter rowSorter = new TableRowSorter();
    private javax.swing.table.DefaultTableModel tableModel=getDefaultTableModel();
    private javax.swing.table.DefaultTableModel getDefaultTableModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][][][][][][][][]{},
                new String[] {"No Transaksi","Tanggal","Item","Total","Diskon","Total Bayar","Dibayar","Kembalian","Kasir"}
        ){
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
    
    private javax.swing.table.DefaultTableModel tablePane=getDefaultTableModel1();
    private javax.swing.table.DefaultTableModel getDefaultTableModel1(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][][][][]{},
                new String[] {"Kode Barang","Nama Barang","Harga","Jumlah","Total"}
        ){
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
    
    String data[] = new String[9];
    public FLaporanTransaksi() {
        initComponents();
        
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPasssword");
        TabelData.setModel(tableModel);
        settableload();
        sistemcari();
        txt_cari.requestFocus();
    }
    
    private void settableload(){
        BHapus.setEnabled(false);
        BHapusSemua.setEnabled(false);
        String stat = "";
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            
            Statement stt = kon.createStatement();
            String SQL = "select * from tbtransaksi";
            ResultSet res = stt.executeQuery(SQL);
            while (res.next()){
                data[0]= res.getString(1);
                data[1]= res.getString(2);
                data[2]= res.getString(3); 
                data[3]= res.getString(4);
                data[4]= res.getString(5);
                data[5]= res.getString(6);
                 
                data[6]= res.getString(7);
                data[7]= res.getString(8);
                data[8]= res.getString(9);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
            
        }
        catch(Exception ex){
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BHapusSemua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BHapus1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BHapus.setBackground(new java.awt.Color(204, 204, 204));
        BHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        TabelData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelData.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelData);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Pencarian*");

        txt_cari.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_cari.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("*) Berdasarkan Semua Data");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Klik 2x Untuk Lihat Detail");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BHapusSemua.setBackground(new java.awt.Color(204, 204, 204));
        BHapusSemua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BHapusSemua.setText("Hapus Semua");
        BHapusSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusSemuaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(461, 104));

        jLabel12.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel12.setText("Laporan Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap())
        );

        BHapus1.setBackground(new java.awt.Color(204, 204, 204));
        BHapus1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BHapus1.setText("Lihat Detai Transaksi");
        BHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BHapus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BHapusSemua)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHapusSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(918, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION)
        {
            try{
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database, user, pass);
                Statement stt = kon.createStatement();
                
                String SQL1 = "Delete From tbitemtransaksi where `nofaktur`='"+tableModel.getValueAt(TabelData.getSelectedRow(),0).toString()+"'";
                stt.executeUpdate(SQL1);
                     
                     
                String SQL = "Delete From tbtransaksi where nofaktur='"+tableModel.getValueAt(TabelData.getSelectedRow(), 0).toString()+"'";
                stt.executeUpdate(SQL);
                tableModel.removeRow(row);
                stt.close();
                kon.close();
            }
            catch(Exception ex){
                System.err.println(ex.getMessage());
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus","Berhasil",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void TabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataMouseClicked
        // TODO add your handling code here:
        BHapus.setEnabled(true);
        BHapusSemua.setEnabled(true);
        
        if(evt.getClickCount()==2){
            String[] kolom ={"Kode Barang","Nama Barang","Harga","Jumlah","Total"};
            String data[] = new String[4];
            String val = (String) TabelData.getValueAt(TabelData.getSelectedRow(), 0);
        
            try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            String stat = "";
            Statement stt = kon.createStatement();
            String SQL = "select kode,nama,harga,jumlah,total from tbitemtransaksi where nofaktur = '"+val+"'";
            ResultSet res = stt.executeQuery(SQL);
            while (res.next()){
                data[0]= res.getString(1);
                data[1]= res.getString(2);
                data[2]= res.getString(3);
                data[3]= res.getString(4);
                data[3]= res.getString(4);
                String[] datatab = data;
                tablePane.addRow(data);
            }    
                JTable tabel = new JTable(tablePane);
                
                JPanel panel = new JPanel();
                getContentPane().add(new JScrollPane(tabel),BorderLayout.CENTER);
                getContentPane().add(panel,BorderLayout.PAGE_END);
                JOptionPane.showMessageDialog(panel, tabel);
                   int row = tabel.getRowCount();
                for(int i=0;i<row;i++){
                    tablePane.removeRow(0);
                }
                
            
            res.close();
            stt.close();
            kon.close();
            
        }
        catch(Exception ex){
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        
            
        }
    }//GEN-LAST:event_TabelDataMouseClicked

    private void BHapusSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusSemuaActionPerformed
        // TODO add your handling code here:
        int konfirm=JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Semua Data?", "Hapus Semua Data", JOptionPane.YES_NO_OPTION);
        if(konfirm==JOptionPane.YES_OPTION)
        {
            try{
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database, user, pass);
                Statement stt = kon.createStatement();
                String SQL1 = "Delete From tbitemtransaksi ";
                String SQL = "Delete From tbtransaksi ";

                stt.executeUpdate(SQL1);
                stt.executeUpdate(SQL);
                int row = TabelData.getRowCount();
                for(int i=0;i<row;i++){
                    tableModel.removeRow(0);
                }
                stt.close();
                kon.close();
            }
            catch(Exception ex){
                System.err.println(ex.getMessage());
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus","Berhasil",JOptionPane.INFORMATION_MESSAGE);
            settableload();
            txt_cari.requestFocus();
        }

    }//GEN-LAST:event_BHapusSemuaActionPerformed

    private void BHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapus1ActionPerformed
        // TODO add your handling code here:
        new FItemTransaksi().show();
    }//GEN-LAST:event_BHapus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLaporanTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BHapus1;
    private javax.swing.JButton BHapusSemua;
    private javax.swing.JTable TabelData;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables


 public void sistemcari(){
      rowSorter = new TableRowSorter(tableModel);
        TabelData.setRowSorter(rowSorter);
 
        txt_cari.getDocument().addDocumentListener(new DocumentListener() {
 
         
            @Override
            public void insertUpdate(DocumentEvent e) {
                changedUpdate(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                changedUpdate(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                String filter = txt_cari.getText();
                if (filter == null) {
                    rowSorter.setRowFilter(RowFilter.regexFilter(null));
                } else {
                    char[] charArray = filter.toCharArray();
                    String[] stringArray = new String[charArray.length];
 
                    for (int i = 0; i < stringArray.length; i++) {
                        stringArray[i] = "[" + Character.toUpperCase(charArray[i])
                                + Character.toLowerCase(charArray[i]) + "]";
                    }
 
                    String regex = "";
                    for (String string : stringArray) {
                        regex += string;
                    }
 
                    try {
                        rowSorter.setRowFilter(RowFilter.regexFilter(regex));
                    } catch (PatternSyntaxException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
}
 
}
