/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AcePC
 */
public class FTambahBarang extends javax.swing.JFrame {
     koneksi dbsetting;
    String driver,database,user,pass;
    Object tabel;
    private TableRowSorter rowSorter = new TableRowSorter();
    /**
     * Creates new form FTambahBarang
     */
    String data[] = new String[6];
    private javax.swing.table.DefaultTableModel tableModel=getDefaultTableModel();
    private javax.swing.table.DefaultTableModel getDefaultTableModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][][][][][]{},
                new String[] {"Kode Barang","Nama Barang","Tanggal Beli","Harga Beli","Stok","Harga Jual"}
        ){
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
    
    public FTambahBarang() {
        initComponents();
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPasssword");
        tampilan();
    }
    
    private void tampilan(){
        TBarang.setModel(tableModel);
        TFNamaBrg.requestFocus();
        TFCari.setDocument(new SaringKarakter().getToUpperCase());
        TFNamaBrg.setDocument(new SaringKarakter().getToUpperCase());
        settableload();
        EnableFalse();
        sistemcari();
        
    }
    
    private void settableload(){
        nofaktur();gettanggal();
        String stat = "";
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            
            Statement stt = kon.createStatement();
            String SQL = "select * from tbbarang order by kode desc";
            ResultSet res = stt.executeQuery(SQL);
            while (res.next()){
                data[0]= res.getString(1);
                data[1]= res.getString(2);
                data[2]= res.getString(3);
                data[3]= res.getString(4);
                data[4]= res.getString(5);
                data[5]= res.getString(6);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
            
        }
        catch(Exception ex){
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LKode = new javax.swing.JLabel();
        TFNamaBrg = new javax.swing.JTextField();
        TFHargaBeli = new javax.swing.JTextField();
        TFStok = new javax.swing.JTextField();
        TFHargaJual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TFCari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBarang = new javax.swing.JTable();
        BEdit = new javax.swing.JButton();
        BSave = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();
        BNew = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        TFDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(461, 104));

        jLabel12.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel12.setText("Data Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel1.setText("Kode Barang");

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Beli");

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel4.setText("Harga Beli");

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel5.setText("Stok");

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel6.setText("Harga Jual");

        LKode.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        LKode.setForeground(new java.awt.Color(255, 0, 51));
        LKode.setText("Kode");

        TFNamaBrg.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N

        TFHargaBeli.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        TFHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFHargaBeliActionPerformed(evt);
            }
        });
        TFHargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFHargaBeliKeyTyped(evt);
            }
        });

        TFStok.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        TFStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFStokKeyTyped(evt);
            }
        });

        TFHargaJual.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        TFHargaJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFHargaJualKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel8.setText("/ satuan");

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel9.setText("/ satuan");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFCari.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel10.setText("Cari Barang");

        TBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBarang);

        BEdit.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        BEdit.setText("EDIT");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });

        BSave.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        BSave.setText("SAVE");
        BSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaveActionPerformed(evt);
            }
        });

        BDelete.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        BDelete.setText("DELETE");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        BNew.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        BNew.setText("NEW");
        BNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNewActionPerformed(evt);
            }
        });

        BCancel.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        BCancel.setText("CANCEL");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TFCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BNew)
                        .addGap(10, 10, 10)
                        .addComponent(BDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BEdit)
                        .addGap(10, 10, 10)
                        .addComponent(BSave)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BDelete, BEdit, BNew, BSave});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TFCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSave)
                    .addComponent(BNew)
                    .addComponent(BDelete))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BDelete, BEdit, BNew, BSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TFDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TFNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TFHargaJual))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TFStok, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(LKode)
                    .addComponent(TFHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(TFHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(716, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFHargaBeliActionPerformed

    private void TBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBarangMouseClicked
         try {
             tampil_field();
             BEdit.setEnabled(true);
             BDelete.setEnabled(true);
             BSave.setEnabled(false);
             aktiftext();
         } catch (ParseException ex) {
             Logger.getLogger(FTambahBarang.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_TBarangMouseClicked

    private void BSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaveActionPerformed
        // TODO add your handling code here:
        
        String data[]=new String[6];
        if((TFNamaBrg.getText().isEmpty())|| (TFHargaBeli.getText().isEmpty())|| (TFStok.getText().isEmpty())|| (TFHargaJual.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong, Silahkan dilengkapi");
            TFNamaBrg.requestFocus();
        }
        else{
            try{
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database,user,pass);
                String tampilan = "yyyy-MM-dd";
                SimpleDateFormat format = new SimpleDateFormat(tampilan);
                String tanggal = String.valueOf(format.format(TFDate.getDate()));
                
                Statement stt = kon.createStatement();
                String SQL = "INSERT INTO tbbarang(kode,nama,tanggal,harga_beli,jumlah,harga_jual) "
                             + "VALUES "
                            + "('"+LKode.getText()+"',"
                            + "'"+TFNamaBrg.getText()+"',"
                            + "'"+tanggal+"',"
                            + "'"+TFHargaBeli.getText()+"',"
                            + "'"+TFStok.getText()+"',"
                            + "'"+TFHargaJual.getText()+"')";
                stt.executeUpdate(SQL);
                data[0]= LKode.getText();
                data[1]= TFNamaBrg.getText();
                data[2]= tanggal;
                data[3]= TFHargaBeli.getText();
                data[4]= TFStok.getText();
                data[5]= TFHargaBeli.getText();
                
                tableModel.insertRow(0, data);
                stt.close();
                kon.close();
                cleartext();
                int konfirmasi=JOptionPane.showConfirmDialog(null, "Data Berhasil Ditambahkan \n Tambah Data Lagi?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                
                if(konfirmasi==JOptionPane.YES_OPTION){
                    EnableTrue();
                }
                else{
                    EnableFalse();
                }
                
            }catch(Exception ex){JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            TFNamaBrg.requestFocus();
            }
        }
    }//GEN-LAST:event_BSaveActionPerformed

    private void BNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNewActionPerformed
        // TODO add your handling code here:
        EnableTrue();
        BDelete.setEnabled(false);
        BEdit.setEnabled(false);
    }//GEN-LAST:event_BNewActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        EnableFalse();
    }//GEN-LAST:event_BCancelActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        // TODO add your handling code here:
        TFCari.requestFocus();
        int konfirmasi=JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(konfirmasi==JOptionPane.YES_OPTION)
            {
                try{
                    Class.forName(driver);
                    Connection kon = DriverManager.getConnection(database, user, pass);
                    Statement stt = kon.createStatement();
                     String SQL1 = "Delete From `tbhistorystok`" 
                                  + "where "
                                  + "`kode`='"+tableModel.getValueAt(row,0).toString()+"'";
                     stt.executeUpdate(SQL1);
                     
                     String SQL   = "DELETE FROM `tbbarang` "
                                   + "WHERE" 
                                   + "`kode`='"+tableModel.getValueAt(row,0).toString()+"'";
                    stt.executeUpdate(SQL);
                    tableModel.removeRow(row);
                    stt.close();
                    kon.close();
                    EnableFalse();
                }
                catch(Exception ex){
                    System.err.println(ex.getMessage());
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus","Berhasil",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_BDeleteActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(null, "Yakin Ingin Mengubah Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(konfirmasi==JOptionPane.YES_OPTION)
            {
                
        
                if((TFNamaBrg.getText().isEmpty())|| (TFHargaBeli.getText().isEmpty())|| (TFStok.getText().isEmpty())|| (TFHargaJual.getText().isEmpty())){
                    JOptionPane.showMessageDialog(null, "Data tidak boleh kosong, Silahkan dilengkapi");
                    TFNamaBrg.requestFocus();
                }
                else{
                    try{
                        String tampilan = "yyyy-MM-dd";
                        SimpleDateFormat format = new SimpleDateFormat(tampilan);
                        String tanggal = String.valueOf(format.format(TFDate.getDate()));
                
                        Class.forName(driver);
                        Connection kon = DriverManager.getConnection(database,user,pass);
                        Statement stt = kon.createStatement();
                        String SQL = "UPDATE `tbbarang` "
                                     + "SET `kode`='"+LKode.getText()+"',"
                                     + "`nama`='"+TFNamaBrg.getText()+"', "
                                     + "`tanggal`='"+tanggal+"', "
                                     + "`harga_beli`='"+TFHargaBeli.getText()+"', "
                                     + "`jumlah`='"+TFStok.getText()+"', "
                                     + "`harga_jual`='"+TFHargaJual.getText()+"' "
                                     + "WHERE "
                                     + "`kode`='"+tableModel.getValueAt(row, 0).toString()+"';";
                        stt.executeUpdate(SQL);
                        data[0]= LKode.getText();
                        data[1]= TFNamaBrg.getText();
                        data[2]= tanggal;
                        data[3]= TFHargaBeli.getText();
                        data[4]= TFStok.getText();
                        data[5]= TFHargaBeli.getText();
                        tableModel.removeRow(row);
                        tableModel.insertRow(row, data);
                        stt.close();
                        kon.close();
                        EnableFalse();
                    }
                    catch(Exception ex){
                        System.err.println(ex.getMessage());
                    }
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah","Berhasil",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_BEditActionPerformed

    private void TFHargaBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFHargaBeliKeyTyped
        // TODO add your handling code here:
                        char karakter = evt.getKeyChar();
        if(!(((karakter>='0') && (karakter <= '9') || karakter == KeyEvent.VK_BACK_SPACE || (karakter == KeyEvent.VK_DELETE)|| karakter==KeyEvent.VK_ENTER))){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_TFHargaBeliKeyTyped

    private void TFStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFStokKeyTyped
        // TODO add your handling code here:
                        char karakter = evt.getKeyChar();
        if(!(((karakter>='0') && (karakter <= '9') || karakter == KeyEvent.VK_BACK_SPACE || (karakter == KeyEvent.VK_DELETE)|| karakter==KeyEvent.VK_ENTER))){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_TFStokKeyTyped

    private void TFHargaJualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFHargaJualKeyTyped
        // TODO add your handling code here:
                        char karakter = evt.getKeyChar();
        if(!(((karakter>='0') && (karakter <= '9') || karakter == KeyEvent.VK_BACK_SPACE || (karakter == KeyEvent.VK_DELETE)|| karakter==KeyEvent.VK_ENTER))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TFHargaJualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTambahBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BDelete;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BNew;
    private javax.swing.JButton BSave;
    private javax.swing.JLabel LKode;
    private javax.swing.JTable TBarang;
    private javax.swing.JTextField TFCari;
    private com.toedter.calendar.JDateChooser TFDate;
    private javax.swing.JTextField TFHargaBeli;
    private javax.swing.JTextField TFHargaJual;
    private javax.swing.JTextField TFNamaBrg;
    private javax.swing.JTextField TFStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void nofaktur(){
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            
            Statement stt = kon.createStatement();
            String SQL = "SELECT MAX(RIGHT(kode,7)) AS NO FROM tbbarang";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()){
                if(res.first()==false){
                    LKode.setText("BR0000001");
                }
                else{
                    res.last();
                    int auto = res.getInt(1)+1;
                    String no = String.valueOf(auto);
                    int noLong = no.length();
                    for(int a=0;a<7-noLong;a++){
                        no = "0"+no;
                    }
                    LKode.setText("BR"+no);
                }
            }
            res.close();
            stt.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void gettanggal(){
        Date ys = new Date();
        TFDate.setDate(ys);
    }
    
    public void cleartext(){
        TFNamaBrg.requestFocus();
        nofaktur();gettanggal();
        TFNamaBrg.setText("");
        TFHargaBeli.setText("");
        TFStok.setText("");
        TFHargaJual.setText("");
    }
    
    public void aktiftext(){
        TFNamaBrg.setEnabled(true);
        TFDate.setEnabled(true);
        TFHargaBeli.setEnabled(true);
        TFStok.setEnabled(true);
        TFHargaJual.setEnabled(true);
    }
    
    public void EnableFalse(){
        cleartext();
        TFCari.requestFocus();
        BDelete.setEnabled(false);
        BEdit.setEnabled(false);
        BSave.setEnabled(false);
        TFNamaBrg.setEnabled(false);
        TFDate.setEnabled(false);
        TFHargaBeli.setEnabled(false);
        TFStok.setEnabled(false);
        TFHargaJual.setEnabled(false);
    }
    
    public void EnableTrue(){
        cleartext();
        TFNamaBrg.requestFocus();
        BSave.setEnabled(true);
        TFNamaBrg.setEnabled(true);
        TFDate.setEnabled(true);
        TFHargaBeli.setEnabled(true);
        TFStok.setEnabled(true);
        TFHargaJual.setEnabled(true);
    }
    
    int row = 0;
    public void tampil_field() throws ParseException{
        row = TBarang.getSelectedRow();
        String tanggal = tableModel.getValueAt(row,2).toString();
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        
        LKode.setText(tableModel.getValueAt(row, 0).toString());
        TFNamaBrg.setText(tableModel.getValueAt(row, 1).toString());
        TFDate.setDate(date);
        TFHargaBeli.setText(tableModel.getValueAt(row, 3).toString());
        TFStok.setText(tableModel.getValueAt(row, 4).toString());
        TFHargaJual.setText(tableModel.getValueAt(row, 5).toString());
        
    }
 
    public void sistemcari(){
      rowSorter = new TableRowSorter(tableModel);
        TBarang.setRowSorter(rowSorter);
 
        TFCari.getDocument().addDocumentListener(new DocumentListener() {
 
         
            @Override
            public void insertUpdate(DocumentEvent e) {
                changedUpdate(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                changedUpdate(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                String filter = TFCari.getText();
                if (filter == null) {
                    rowSorter.setRowFilter(RowFilter.regexFilter(null));
                } else {
                    char[] charArray = filter.toCharArray();
                    String[] stringArray = new String[charArray.length];
 
                    for (int i = 0; i < stringArray.length; i++) {
                        stringArray[i] = "[" + Character.toUpperCase(charArray[i])
                                + Character.toLowerCase(charArray[i]) + "]";
                    }
 
                    String regex = "";
                    for (String string : stringArray) {
                        regex += string;
                    }
 
                    try {
                        rowSorter.setRowFilter(RowFilter.regexFilter(regex));
                    } catch (PatternSyntaxException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
}
    
    
}
